# Generated by Django 4.2.7 on 2023-11-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_track_delete_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='catalogue/audio/'),
        ),
    ]
