# Generated by Django 4.2.7 on 2023-11-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_artist_remove_track_url_alter_track_image_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='title',
            new_name='name',
        ),
    ]
