# Generated by Django 4.2.7 on 2023-11-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_rename_title_track_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='name',
        ),
    ]
