# Generated by Django 4.2.7 on 2023-12-05 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_remove_artist_description_remove_track_audio_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artists',
        ),
    ]
