# Generated by Django 4.2.7 on 2023-12-06 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_rename_artist_album_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(default='waitmattno', on_delete=django.db.models.deletion.CASCADE, to='catalogue.artist'),
            preserve_default=False,
        ),
    ]
